---
title: "Przyklady"
author: "Michał Burdukiewicz"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(plotly)
theme_set(theme_bw())
```

```{r}
set.seed(15390)
dat <- droplevels(diamonds[sample(1L:nrow(diamonds), 100), ])
```

\newpage

## Rysunek 1

### Przed poprawkami

```{r}
ggplot(dat, aes(x = cut, y = price)) +
  geom_boxplot(outlier.color = NA) +
  geom_point(position = "jitter") 

```

### Po poprawkach

```{r}
ggplot(dat, aes(x = cut, y = price)) +
  geom_boxplot() +
  ggtitle("Price of diamonds depending on the cut") +
  scale_x_discrete("Cut") +
  scale_y_continuous("Price [USD]")
```


\newpage

## Rysunek 2

### Przed poprawkami

```{r}
group_by(dat, cut, clarity) %>% 
  summarise(count = length(price)) %>% 
  ggplot(aes(x = cut, y = clarity, fill = count)) +
  geom_tile(color = "black") +
  scale_fill_gradient(low = "white", high = "black")
```

### Po poprawkach

```{r}
group_by(dat, cut, clarity) %>% 
  summarise(count = length(price)) %>% 
  ggplot(aes(x = cut, y = clarity, fill = count, label = count)) +
  geom_tile(color = "black") +
  geom_label(fill = "white") +
  scale_fill_gradient(low = "#deebf7", high = "#3182bd")
```

\newpage

## Rysunek 3

### Przed poprawkami

```{r}
ggplot(dat, aes(x = carat, y = price, shape = clarity)) +
  geom_point()
```

### Po poprawkach

```{r}
ggplot(dat, aes(x = carat, y = price)) +
  geom_point() +
  facet_wrap(~ clarity, labeller = label_both)
```

\newpage

## Rysunek 4


### Przed poprawkami

```{r}
ggplot(dat, aes(x = carat, y = price, shape = cut)) +
  geom_point() +
  facet_wrap(~ clarity, labeller = label_both) 
```

### Po poprawkach

```{r,fig.height=8}
p <- ggplot(dat, aes(x = carat, y = price, shape = cut)) +
  geom_point() +
  facet_wrap(~ clarity, labeller = label_both, ncol = 2) 

ggplotly(p)
```

\newpage

## Rysunek 5

### Przed poprawkami

```{r,fig.height=7}
ggplot(dat, aes(x = color)) +
  geom_bar() +
  facet_grid(cut ~ clarity, labeller = label_both) 
```


### Po poprawkach

```{r,fig.height=7}
ggplot(dat, aes(x = color, fill = cut)) +
  geom_bar(position = "dodge") +
  facet_wrap( ~ clarity, labeller = label_both) 
```
\newpage

## Rysunek 6


### Przed poprawkami

```{r}
ggplot(dat, aes(x = price)) +
  geom_histogram() +
  facet_wrap(~ cut, labeller = label_both)
```

### Po poprawkach

```{r}
select(dat, price, cut) %>% 
  group_by(cut) %>% 
  mutate(med = median(price)) %>% 
  ggplot(aes(x = price)) +
  geom_histogram() +
  scale_x_continuous(limits = c(0, 19000)) +
  scale_y_continuous(limits = c(0, 13)) +
  geom_vline(aes(xintercept = med), color = "red") +
  facet_wrap(~ cut, labeller = label_both, scales = "free")
```
